"""
Canonical figure-generation script for Figures 3, 4, and S6.

Produces the final versions of:
  Figure 3  (Simulation 2: brain-size trajectory under ceiling lift)
    ← experiment2_{control,treatment}_trajectories.csv.gz
  Figure 4  (Simulation 3: cooperative-care vs care-independent energetic routes)
    ← Data_S7_Mixed_Summary.csv
  Figure S6 (Robustness: gradual ceiling ramp)
    ← gradual_ceiling_{control,treatment}_trajectories.csv.gz

Figures 1-2 are generated by the Simulation 1 pipeline.
Figures S1-S3, S5 are generated by childhood_first_simulation.py.
Figure S4 is generated by visualize_alternative_models.py.

Terminology: Phase 1 / Phase 2 / Phase 3 throughout.
Color scheme: orange (#E69F00) = control, blue (#0072B2) = treatment.
"""
import argparse
import numpy as np, pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import Patch
from pathlib import Path
import warnings; warnings.filterwarnings('ignore')

COLORS = {'control':'#E69F00','treatment':'#0072B2','highlight':'#D55E00','neutral':'#666666'}
plt.rcParams.update({
    'font.family':'sans-serif','font.sans-serif':['Arial','Helvetica','DejaVu Sans'],
    'font.size':10,'axes.titlesize':12,'axes.labelsize':11,
    'xtick.labelsize':9,'ytick.labelsize':9,'legend.fontsize':9,
    'figure.dpi':300,'savefig.dpi':300,'savefig.bbox':'tight',
    'savefig.facecolor':'white','axes.linewidth':1.0,
    'axes.spines.top':False,'axes.spines.right':False,
    'axes.facecolor':'white','figure.facecolor':'white',
})
LW=2; AB=0.25; AS=0.5; SS=35
PNL=dict(loc='left',fontweight='bold',fontsize=14)

def read_trajectory_parts(trajectory_files):
    """Read and concatenate condition-specific trajectory files."""
    return pd.concat(
        [pd.read_csv(path) for path in trajectory_files],
        ignore_index=True,
    )


def figure3_exp2(out, trajectory_files):
    """Figure 3: Simulation 2 — Brain expansion under cooperative care."""
    Path(out).mkdir(parents=True, exist_ok=True)
    traj = read_trajectory_parts(trajectory_files)
    n=100
    def agg(g):
        df=traj[traj['group']==g].groupby('generation').agg(B=('B_mean','mean'),Bsd=('B_mean','std')).reset_index()
        df['sem']=df['Bsd']/np.sqrt(n); return df
    c=agg('control'); t=agg('treatment')
    
    fig,ax=plt.subplots(figsize=(8,5)); plt.subplots_adjust(top=0.82)
    ck=c['generation']/1000; tk=t['generation']/1000
    ax.fill_between(ck,c['B']-c['sem'],c['B']+c['sem'],alpha=AB,color=COLORS['control'],lw=0)
    ax.fill_between(tk,t['B']-t['sem'],t['B']+t['sem'],alpha=AB,color=COLORS['treatment'],lw=0)
    ax.plot(ck,c['B'],color=COLORS['control'],lw=LW,label='Control')
    ax.plot(tk,t['B'],color=COLORS['treatment'],lw=LW,label='Treatment (cooperative care)')
    ax.axvline(10,color=COLORS['neutral'],ls='--',alpha=0.5,lw=1)
    ax.axvline(100,color=COLORS['neutral'],ls='--',alpha=0.5,lw=1)
    ax.axhline(50,color=COLORS['control'],ls=':',alpha=0.5,lw=1)
    ax.axhline(110,color=COLORS['treatment'],ls=':',alpha=0.5,lw=1)
    ax.set_xlim(0,200); ax.set_ylim(0,120)
    ax.annotate(r'$B_{max}=50$',xy=(198,47),ha='right',va='top',fontsize=9,color=COLORS['control'],fontweight='bold')
    ax.annotate(r'$B_{max}=110$',xy=(198,107),ha='right',va='top',fontsize=9,color=COLORS['treatment'],fontweight='bold')
    ax.set_xlabel(r'Generation ($\times 10^3$)'); ax.set_ylabel('Mean Brain Size (B)')
    ax.legend(loc='upper left',frameon=False,fontsize=9,bbox_to_anchor=(0.01,0.78))
    for xf,lab in [(0.04,'Phase 1'),(0.30,'Phase 2'),(0.75,'Phase 3')]:
        ax.text(xf,1.09,lab,transform=ax.transAxes,ha='center',va='bottom',fontsize=10,color=COLORS['neutral'],fontweight='bold',style='italic')
    for xf,lab in [(0.30,'Care divergence'),(0.75,'Ceiling lift')]:
        ax.text(xf,1.01,lab,transform=ax.transAxes,ha='center',va='bottom',fontsize=8,color=COLORS['neutral'])
    plt.savefig(f'{out}/Figure3_experiment2.pdf',format='pdf')
    plt.close(); print("  Fig 3 saved")

def figure4_exp3(out, summary_file):
    """Figure 4: Simulation 3 — Two emergent routes (bars + trait space)."""
    Path(out).mkdir(parents=True, exist_ok=True)
    mixed=pd.read_csv(summary_file); n=100
    mc=mixed[mixed['group']=='control']; mt=mixed[mixed['group']=='treatment']
    def msem(v): return v.mean(),v.std(ddof=1)/np.sqrt(n)
    
    fig=plt.figure(figsize=(11,5))
    gs=gridspec.GridSpec(1,2,width_ratios=[0.8,1.1],wspace=0.35)
    
    # Panel A: Childhood bars
    ax_a=fig.add_subplot(gs[0])
    Lc,Lce=msem(mc['phase3_L']); Lt,Lte=msem(mt['phase3_L'])
    bars=ax_a.bar([0,1],[Lt,Lc],yerr=[Lte,Lce],capsize=5,
        color=[COLORS['treatment'],COLORS['control']],alpha=0.85,edgecolor='black',linewidth=1,width=0.6)
    top=max(Lt+Lte,Lc+Lce)+0.3
    ax_a.plot([0,1],[top,top],'k-',lw=0.8)
    ax_a.text(0.5,top+0.1,'***',ha='center',fontsize=11,fontweight='bold')
    ax_a.set_xticks([0,1]); ax_a.set_xticklabels(['Cooperative-\ncare route','Care-independent\nenergetic route'],fontsize=9)
    ax_a.set_ylabel('Childhood Duration (L)')
    ax_a.set_ylim(0,top+1.5); ax_a.set_title('A',**PNL)
    ax_a.text(0.5,0.02,r'Brain expansion similar'+'\n'+r'($\Delta B \approx 14$, $p$ = 0.85)',
        transform=ax_a.transAxes,ha='center',va='bottom',fontsize=8,color=COLORS['neutral'],style='italic',
        bbox=dict(boxstyle='round,pad=0.3',facecolor='white',edgecolor=COLORS['neutral'],alpha=0.7,lw=0.5))
    
    # Panel B: Trait space
    ax_b=fig.add_subplot(gs[1])
    ax_b.scatter(mc['phase3_B'],mc['phase3_L'],c=COLORS['control'],alpha=AS,s=SS,edgecolors='white',lw=0.5)
    ax_b.scatter(mt['phase3_B'],mt['phase3_L'],c=COLORS['treatment'],alpha=AS,s=SS,edgecolors='white',lw=0.5)
    mcx,mcy=mc['phase3_B'].mean(),mc['phase3_L'].mean()
    mtx,mty=mt['phase3_B'].mean(),mt['phase3_L'].mean()
    ax_b.scatter(mcx,mcy,c=COLORS['control'],s=200,marker='D',edgecolors='black',linewidth=1.5,zorder=5)
    ax_b.scatter(mtx,mty,c=COLORS['treatment'],s=200,marker='D',edgecolors='black',linewidth=1.5,zorder=5)
    ax_b.annotate('Cooperative-care\nroute',xy=(mtx,mty),xytext=(mtx+12,mty+2),fontsize=9,
        color=COLORS['treatment'],fontweight='bold',ha='left',
        arrowprops=dict(arrowstyle='-',color=COLORS['treatment'],lw=0.8))
    ax_b.annotate('Care-independent\nenergetic route',xy=(mcx,mcy),xytext=(mcx+12,mcy-1.5),fontsize=9,
        color=COLORS['control'],fontweight='bold',ha='left',
        arrowprops=dict(arrowstyle='-',color=COLORS['control'],lw=0.8))
    ax_b.set_xlabel('Brain Size (B)'); ax_b.set_ylabel('Childhood Duration (L)')
    ax_b.set_title('B',**PNL)
    
    plt.savefig(f'{out}/Figure4_experiment3.pdf',format='pdf')
    plt.savefig(f'{out}/Figure4_experiment3.png',format='png')
    plt.close(); print("  Fig 4 saved")

def figureS6(out, trajectory_files):
    """Fig S6: Gradual ramp robustness check — harmonized."""
    Path(out).mkdir(parents=True, exist_ok=True)
    traj=read_trajectory_parts(trajectory_files); n=100
    def agg(g):
        df=traj[traj['group']==g].groupby('generation').agg(B=('B_mean','mean'),Bsd=('B_mean','std')).reset_index()
        df['sem']=df['Bsd']/np.sqrt(n); return df
    c=agg('control'); t=agg('treatment')
    fig,ax=plt.subplots(figsize=(9,5)); plt.subplots_adjust(top=0.82)
    ck=c['generation']/1000; tk=t['generation']/1000
    ax.fill_between(ck,c['B']-c['sem'],c['B']+c['sem'],alpha=AB,color=COLORS['control'],lw=0)
    ax.fill_between(tk,t['B']-t['sem'],t['B']+t['sem'],alpha=AB,color=COLORS['treatment'],lw=0)
    ax.plot(ck,c['B'],color=COLORS['control'],lw=LW,label='Control')
    ax.plot(tk,t['B'],color=COLORS['treatment'],lw=LW,label='Treatment (cooperative care)')
    ax.axvline(10,color=COLORS['neutral'],ls='--',alpha=0.5,lw=1)
    ax.axvline(100,color=COLORS['neutral'],ls='--',alpha=0.5,lw=1)
    ax.axhline(50,color=COLORS['control'],ls=':',alpha=0.5,lw=1)
    ax.axhline(110,color=COLORS['treatment'],ls=':',alpha=0.5,lw=1)
    ax.axvspan(100,150,alpha=0.06,color=COLORS['treatment'])
    ax.annotate('Ceiling ramp\n(50k gen)',xy=(125,47),ha='center',va='top',fontsize=8,color=COLORS['treatment'],style='italic')
    ax.set_xlim(0,200); ax.set_ylim(0,120)
    ax.annotate(r'$B_{max}=50$',xy=(198,47),ha='right',va='top',fontsize=9,color=COLORS['control'],fontweight='bold')
    ax.annotate(r'$B_{max}=110$',xy=(198,107),ha='right',va='top',fontsize=9,color=COLORS['treatment'],fontweight='bold')
    ax.set_xlabel(r'Generation ($\times 10^3$)'); ax.set_ylabel('Mean Brain Size (B)')
    ax.legend(loc='upper left',frameon=False,bbox_to_anchor=(0.02,0.80))
    for xf,lab in [(0.04,'Phase 1'),(0.27,'Phase 2'),(0.75,'Phase 3')]:
        ax.text(xf,1.06,lab,transform=ax.transAxes,ha='center',va='bottom',fontsize=10,color=COLORS['neutral'],fontweight='bold',style='italic')
    for xf,lab in [(0.27,'Care divergence'),(0.75,'Gradual ceiling lift')]:
        ax.text(xf,0.98,lab,transform=ax.transAxes,ha='center',va='bottom',fontsize=8,color=COLORS['neutral'])
    plt.savefig(f'{out}/FigureS6_gradual_ramp.pdf',format='pdf')
    plt.close(); print("  Fig S6 saved")

if __name__=='__main__':
    parser = argparse.ArgumentParser(
        description='Regenerate Figures 3, 4, and Figure 3—figure supplement 1.'
    )
    parser.add_argument('--data-dir', default='.',
                        help='Directory containing the repository data files (default: repository root)')
    parser.add_argument('--output-dir', default='figures/generated',
                        help='Directory for generated PDF figures')
    args = parser.parse_args()
    data_dir = Path(args.data_dir)
    out = args.output_dir
    print("Generating final figures...")
    figure3_exp2(out, (
        data_dir / 'experiment2_control_trajectories.csv.gz',
        data_dir / 'experiment2_treatment_trajectories.csv.gz',
    ))
    figure4_exp3(out, data_dir / 'Data_S7_Mixed_Summary.csv')
    figureS6(out, (
        data_dir / 'gradual_ceiling_control_trajectories.csv.gz',
        data_dir / 'gradual_ceiling_treatment_trajectories.csv.gz',
    ))
    print("Done.")
