"""
Auxiliary plotting companion script for alternative model analyses.

Renders SI figures from outputs generated by alternative_models_analysis.py.
Produces Figure S4 (alternative model comparison).

This is a visualization-only script; it does not perform any simulation
or statistical analysis.
"""
#!/usr/bin/env python3
"""
visualize_alternative_models.py

Creates publication-quality figures for the Alternative Models Analysis
========================================================================

This script generates:
1. Figure S4a: Bar chart comparing ΔL% and ΔB% across model specifications
2. Figure S4b: Forest plot showing effect sizes with confidence intervals
3. Summary table visualization

USAGE
-----
    python visualize_alternative_models.py

    # With custom input file:
    python visualize_alternative_models.py --input alternative_models_results.csv

OUTPUT
------
    Fig_S4a_alternative_models_comparison.png
    Fig_S4a_alternative_models_comparison.pdf
    Fig_S4b_alternative_models_forest.png
    Fig_S4b_alternative_models_forest.pdf

Author: Tobias Grossmann (tg3ny@virginia.edu)
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.lines import Line2D
import argparse
import os

# Set publication-quality defaults
plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.sans-serif': ['DejaVu Sans', 'Arial', 'Helvetica'],
    'font.size': 10,
    'axes.labelsize': 11,
    'axes.titlesize': 12,
    'xtick.labelsize': 9,
    'ytick.labelsize': 9,
    'legend.fontsize': 9,
    'figure.dpi': 150,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
    'axes.spines.top': False,
    'axes.spines.right': False,
})


def load_results(filepath='alternative_models_results.csv'):
    """Load alternative models results from CSV.
    
    Supports both original output name and Data_S4 submission name.
    """
    candidates = [
        filepath,
        'Data_S4_Alternative_Models.csv',
        'data/Data_S4_Alternative_Models.csv',
        'results/Data_S4_Alternative_Models.csv',
        'alternative_models_results.csv',
        'data/alternative_models_results.csv',
        'results/alternative_models_results.csv',
    ]
    
    for path in candidates:
        if os.path.exists(path):
            df = pd.read_csv(path)
            print(f"  Loaded: {path}")
            break
    else:
        raise FileNotFoundError(
            f"Could not find alternative models results. Tried: {', '.join(candidates)}"
        )
    
    # Clean up model names for display
    df['model_short'] = df['model'].str.replace(r'^\d+\.\s*', '', regex=True)
    df['model_short'] = df['model_short'].str.replace(' (Original)', '', regex=False)
    df['model_short'] = df['model_short'].str.replace('NULL CONTROL', 'Null Control', regex=False)
    
    return df


def create_comparison_barplot(df, output_dir='.'):
    """
    Create Figure S4a: Side-by-side bar chart comparing ΔL% and ΔB% across models.
    """
    fig, axes = plt.subplots(1, 2, figsize=(10, 5))
    
    models = df['model_short'].values
    x = np.arange(len(models))
    width = 0.6
    
    # Colors
    colors_L = ['#2E86AB' if not df.iloc[i]['model_short'] == 'Null Control' else '#95a5a6' 
                for i in range(len(df))]
    colors_B = ['#A23B72' if abs(df.iloc[i]['delta_B_pct']) >= 2 else '#28a745' 
                for i in range(len(df))]
    
    # Panel A: Childhood Extension (ΔL%)
    ax1 = axes[0]
    bars1 = ax1.bar(x, df['delta_L_pct'], width, color=colors_L, edgecolor='black', linewidth=0.5)
    
    # Add significance stars
    for i, (val, p) in enumerate(zip(df['delta_L_pct'], df['p_value_L'])):
        if p < 0.001:
            star = '***'
        elif p < 0.01:
            star = '**'
        elif p < 0.05:
            star = '*'
        else:
            star = 'n.s.'
        ax1.annotate(star, (i, val + 1), ha='center', fontsize=9)
    
    # Add threshold line
    ax1.axhline(y=10, color='red', linestyle='--', linewidth=1.5, alpha=0.7, label='Decoupling threshold (10%)')
    
    ax1.set_ylabel('Childhood Extension (ΔL%)', fontweight='bold')
    ax1.set_xticks(x)
    ax1.set_xticklabels(models, rotation=45, ha='right')
    ax1.set_ylim(0, max(df['delta_L_pct']) * 1.25)
    ax1.legend(loc='upper right', frameon=False)
    ax1.set_title('A. Childhood Extension', fontweight='bold', loc='left')
    
    # Add value labels on bars
    for i, v in enumerate(df['delta_L_pct']):
        ax1.text(i, v/2, f'+{v:.1f}%', ha='center', va='center', fontweight='bold', 
                color='white' if v > 5 else 'black', fontsize=9)
    
    # Panel B: Brain Size Change (ΔB%)
    ax2 = axes[1]
    bars2 = ax2.bar(x, df['delta_B_pct'], width, color=colors_B, edgecolor='black', linewidth=0.5)
    
    # Add equivalence bounds
    ax2.axhline(y=2, color='green', linestyle='--', linewidth=1.5, alpha=0.7)
    ax2.axhline(y=-2, color='green', linestyle='--', linewidth=1.5, alpha=0.7, label='Equivalence bounds (±2%)')
    ax2.axhline(y=0, color='black', linestyle='-', linewidth=0.5, alpha=0.5)
    
    ax2.set_ylabel('Brain Size Change (ΔB%)', fontweight='bold')
    ax2.set_xticks(x)
    ax2.set_xticklabels(models, rotation=45, ha='right')
    ax2.set_ylim(min(df['delta_B_pct']) * 1.3, max(df['delta_B_pct']) + 3)
    ax2.legend(loc='upper right', frameon=False)
    ax2.set_title('B. Brain Size Change', fontweight='bold', loc='left')
    
    # Add value labels on bars
    for i, v in enumerate(df['delta_B_pct']):
        y_pos = v/2 if abs(v) > 1 else (v + 0.5 if v >= 0 else v - 0.5)
        color = 'white' if abs(v) > 2 else 'black'
        ax2.text(i, y_pos, f'{v:+.1f}%', ha='center', va='center', fontweight='bold',
                color=color, fontsize=9)
    
    # Add decoupling indicators
    for i, dec in enumerate(df['decoupling']):
        if dec:
            ax2.annotate('YES', (i, df.iloc[i]['delta_B_pct'] - 1.5), ha='center', 
                        fontsize=14, color='green', fontweight='bold')
    
    plt.tight_layout()
    
    # Save
    for ext in ['png', 'pdf']:
        filepath = os.path.join(output_dir, f'Fig_S4a_alternative_models_comparison.{ext}')
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        print(f'Saved: {filepath}')
    
    plt.close()


def create_forest_plot(df, output_dir='.'):
    """
    Create Figure S4b: Forest plot showing effect sizes (Cohen's d) with interpretation.
    """
    fig, ax = plt.subplots(figsize=(8, 6))
    
    models = df['model_short'].values[::-1]  # Reverse for top-to-bottom display
    d_values = df['cohens_d'].values[::-1]
    decoupling = df['decoupling'].values[::-1]
    
    y_pos = np.arange(len(models))
    
    # Effect size interpretation bands
    ax.axvspan(0, 0.2, alpha=0.1, color='gray', label='Negligible')
    ax.axvspan(0.2, 0.5, alpha=0.15, color='yellow', label='Small')
    ax.axvspan(0.5, 0.8, alpha=0.15, color='orange', label='Medium')
    ax.axvspan(0.8, 2.0, alpha=0.15, color='green', label='Large')
    
    # Plot points
    colors = ['#2E86AB' if dec else '#E74C3C' for dec in decoupling]
    markers = ['o' if dec else 's' for dec in decoupling]
    
    for i, (d, c, m) in enumerate(zip(d_values, colors, markers)):
        ax.scatter(d, y_pos[i], c=c, marker=m, s=150, edgecolors='black', linewidth=1, zorder=5)
        
        # Add confidence interval approximation (rough estimate based on n=30)
        se_d = np.sqrt(2/30 + d**2/(2*30))  # Approximate SE for Cohen's d
        ci_low = d - 1.96 * se_d
        ci_high = d + 1.96 * se_d
        ax.hlines(y_pos[i], ci_low, ci_high, colors=c, linewidth=2, alpha=0.7)
    
    # Reference line at d=0
    ax.axvline(x=0, color='black', linestyle='-', linewidth=1)
    
    # Labels
    ax.set_yticks(y_pos)
    ax.set_yticklabels(models)
    ax.set_xlabel("Cohen's d (Effect Size for Childhood Extension)", fontweight='bold')
    ax.set_title('Effect Sizes Across Alternative Model Specifications', fontweight='bold')
    ax.set_xlim(-0.3, 1.6)
    
    # Add effect size interpretation labels
    ax.text(0.1, len(models) + 0.3, 'Negligible', ha='center', fontsize=8, style='italic')
    ax.text(0.35, len(models) + 0.3, 'Small', ha='center', fontsize=8, style='italic')
    ax.text(0.65, len(models) + 0.3, 'Medium', ha='center', fontsize=8, style='italic')
    ax.text(1.2, len(models) + 0.3, 'Large', ha='center', fontsize=8, style='italic')
    
    # Custom legend
    legend_elements = [
        Line2D([0], [0], marker='o', color='w', markerfacecolor='#2E86AB', 
               markersize=10, markeredgecolor='black', label='Decoupling achieved'),
        Line2D([0], [0], marker='s', color='w', markerfacecolor='#E74C3C', 
               markersize=10, markeredgecolor='black', label='No decoupling'),
    ]
    ax.legend(handles=legend_elements, loc='lower right', frameon=True)
    
    plt.tight_layout()
    
    # Save
    for ext in ['png', 'pdf']:
        filepath = os.path.join(output_dir, f'Fig_S4b_alternative_models_forest.{ext}')
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        print(f'Saved: {filepath}')
    
    plt.close()


def create_summary_figure(df, output_dir='.'):
    """
    Create a comprehensive summary figure combining multiple visualizations.
    """
    fig = plt.figure(figsize=(12, 10))
    
    # Create grid
    gs = fig.add_gridspec(3, 2, height_ratios=[1.2, 1, 0.8], hspace=0.35, wspace=0.3)
    
    models = df['model_short'].values
    x = np.arange(len(models))
    width = 0.35
    
    # ==========================================================================
    # Panel A: Grouped bar chart (ΔL and ΔB side by side)
    # ==========================================================================
    ax1 = fig.add_subplot(gs[0, :])
    
    # Normalize for comparison (optional, using raw values here)
    bars1 = ax1.bar(x - width/2, df['delta_L_pct'], width, label='ΔL% (Childhood)', 
                    color='#2E86AB', edgecolor='black', linewidth=0.5)
    bars2 = ax1.bar(x + width/2, df['delta_B_pct'], width, label='ΔB% (Brain)', 
                    color='#A23B72', edgecolor='black', linewidth=0.5)
    
    # Threshold lines
    ax1.axhline(y=10, color='#2E86AB', linestyle='--', linewidth=1.5, alpha=0.7)
    ax1.axhline(y=2, color='#A23B72', linestyle=':', linewidth=1.5, alpha=0.7)
    ax1.axhline(y=-2, color='#A23B72', linestyle=':', linewidth=1.5, alpha=0.7)
    ax1.axhline(y=0, color='black', linestyle='-', linewidth=0.5)
    
    # Decoupling markers
    for i, dec in enumerate(df['decoupling']):
        if dec:
            ax1.annotate('DECOUPLING', (i, df.iloc[i]['delta_L_pct'] + 3), 
                        ha='center', fontsize=8, color='green', fontweight='bold',
                        bbox=dict(boxstyle='round,pad=0.3', facecolor='lightgreen', alpha=0.7))
    
    ax1.set_ylabel('Change (%)', fontweight='bold')
    ax1.set_xticks(x)
    ax1.set_xticklabels(models)
    ax1.set_title('A. Childhood Extension vs Brain Size Change Across Model Specifications', 
                  fontweight='bold', loc='left', fontsize=11)
    ax1.legend(loc='upper right', frameon=True)
    ax1.set_ylim(-12, 35)
    
    # Add annotations
    ax1.annotate('ΔL ≥ 10% threshold', xy=(4.5, 10), xytext=(4.5, 15),
                fontsize=8, color='#2E86AB',
                arrowprops=dict(arrowstyle='->', color='#2E86AB', lw=1))
    ax1.annotate('±2% equivalence', xy=(4.5, 2), xytext=(4.5, 6),
                fontsize=8, color='#A23B72',
                arrowprops=dict(arrowstyle='->', color='#A23B72', lw=1))
    
    # ==========================================================================
    # Panel B: Effect sizes
    # ==========================================================================
    ax2 = fig.add_subplot(gs[1, 0])
    
    colors = ['#28a745' if d else '#dc3545' for d in df['decoupling']]
    bars = ax2.barh(x, df['cohens_d'], color=colors, edgecolor='black', linewidth=0.5)
    
    # Effect size reference lines
    ax2.axvline(x=0.2, color='gray', linestyle=':', alpha=0.5)
    ax2.axvline(x=0.5, color='gray', linestyle=':', alpha=0.5)
    ax2.axvline(x=0.8, color='gray', linestyle=':', alpha=0.5)
    
    ax2.set_yticks(x)
    ax2.set_yticklabels(models)
    ax2.set_xlabel("Cohen's d", fontweight='bold')
    ax2.set_title("B. Effect Sizes (Cohen's d)", fontweight='bold', loc='left')
    ax2.set_xlim(0, 1.5)
    
    # Add value labels
    for i, v in enumerate(df['cohens_d']):
        ax2.text(v + 0.05, i, f'{v:.2f}', va='center', fontsize=9)
    
    # Effect size interpretation
    ax2.text(0.1, -0.8, 'Small', ha='center', fontsize=8, style='italic', color='gray')
    ax2.text(0.35, -0.8, 'Med', ha='center', fontsize=8, style='italic', color='gray')
    ax2.text(0.65, -0.8, 'Large', ha='center', fontsize=8, style='italic', color='gray')
    
    # ==========================================================================
    # Panel C: P-values (log scale)
    # ==========================================================================
    ax3 = fig.add_subplot(gs[1, 1])
    
    # Convert p-values to -log10 for visualization
    log_p = -np.log10(df['p_value_L'].values + 1e-10)  # Add small value to avoid log(0)
    
    colors = ['#28a745' if p < 0.005 else '#ffc107' if p < 0.05 else '#dc3545' 
              for p in df['p_value_L']]
    bars = ax3.barh(x, log_p, color=colors, edgecolor='black', linewidth=0.5)
    
    # Significance thresholds
    ax3.axvline(x=-np.log10(0.05), color='orange', linestyle='--', linewidth=1.5, 
                label='p = 0.05')
    ax3.axvline(x=-np.log10(0.005), color='red', linestyle='--', linewidth=1.5,
                label='p = 0.005')
    
    ax3.set_yticks(x)
    ax3.set_yticklabels(models)
    ax3.set_xlabel('-log10(p-value)', fontweight='bold')
    ax3.set_title('C. Statistical Significance', fontweight='bold', loc='left')
    ax3.legend(loc='lower right', fontsize=8)
    
    # Add actual p-values as text
    for i, p in enumerate(df['p_value_L']):
        if p < 0.001:
            p_text = '<0.001'
        else:
            p_text = f'{p:.3f}'
        ax3.text(log_p[i] + 0.2, i, f'p={p_text}', va='center', fontsize=8)
    
    # ==========================================================================
    # Panel D: Summary table
    # ==========================================================================
    ax4 = fig.add_subplot(gs[2, :])
    ax4.axis('off')
    
    # Create summary table
    table_data = []
    for _, row in df.iterrows():
        p_str = '<0.001' if row['p_value_L'] < 0.001 else f"{row['p_value_L']:.3f}"
        dec_str = 'YES' if row['decoupling'] else 'NO'
        table_data.append([
            row['model_short'],
            f"+{row['delta_L_pct']:.1f}%",
            f"{row['delta_B_pct']:+.1f}%",
            p_str,
            f"{row['cohens_d']:.2f}",
            dec_str
        ])
    
    columns = ['Model', 'ΔL%', 'ΔB%', 'p(L)', "Cohen's d", 'Decoupling']
    
    table = ax4.table(cellText=table_data, colLabels=columns,
                      loc='center', cellLoc='center',
                      colWidths=[0.25, 0.12, 0.12, 0.12, 0.12, 0.15])
    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1.2, 1.5)
    
    # Style header
    for i in range(len(columns)):
        table[(0, i)].set_facecolor('#2E86AB')
        table[(0, i)].set_text_props(color='white', fontweight='bold')
    
    # Color decoupling column
    for i in range(len(df)):
        if df.iloc[i]['decoupling']:
            table[(i+1, 5)].set_facecolor('#d4edda')
        else:
            table[(i+1, 5)].set_facecolor('#f8d7da')
    
    ax4.set_title('D. Summary Table', fontweight='bold', loc='left', y=0.95)
    
    plt.suptitle('Alternative Model Specifications Analysis\n', fontsize=14, fontweight='bold', y=1.02)
    
    # Save
    for ext in ['png', 'pdf']:
        filepath = os.path.join(output_dir, f'Fig_S4_alternative_models_summary.{ext}')
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        print(f'Saved: {filepath}')
    
    plt.close()


def create_mechanism_diagram(df, output_dir='.'):
    """
    Create a conceptual diagram explaining why only superlinear produces decoupling.
    """
    fig, axes = plt.subplots(1, 3, figsize=(12, 4))
    
    L = np.linspace(0, 20, 100)
    L_max = 20
    r = 0.3
    Sub_care = 0.6
    
    # Panel A: Different functional forms
    ax1 = axes[0]
    
    # Superlinear
    y_super = Sub_care * r * (L/L_max)**1.8 * L_max
    ax1.plot(L, y_super, 'b-', linewidth=2.5, label='Superlinear (e=1.8)')
    
    # Linear
    y_linear = Sub_care * r * L
    ax1.plot(L, y_linear, 'g--', linewidth=2, label='Linear')
    
    # Saturating
    K = 5
    y_sat = Sub_care * r * L_max * L / (L + K)
    ax1.plot(L, y_sat, 'r:', linewidth=2, label='Saturating (K=5)')
    
    ax1.set_xlabel('Childhood Duration (L)', fontweight='bold')
    ax1.set_ylabel('Social Benefit', fontweight='bold')
    ax1.set_title('A. Social Benefit Functions', fontweight='bold', loc='left')
    ax1.legend(loc='upper left', frameon=True)
    ax1.set_xlim(0, 20)
    ax1.set_ylim(0, 4)
    
    # Add annotation about marginal returns
    ax1.annotate('Accelerating\nreturns', xy=(15, 2.5), fontsize=9, color='blue',
                ha='center', style='italic')
    ax1.annotate('Constant\nreturns', xy=(15, 3.6), fontsize=9, color='green',
                ha='center', style='italic')
    ax1.annotate('Diminishing\nreturns', xy=(15, 1.8), fontsize=9, color='red',
                ha='center', style='italic')
    
    # Panel B: Marginal benefit vs cost
    ax2 = axes[1]
    
    # Marginal benefit (derivative)
    dL = 0.01
    mb_super = np.gradient(y_super, dL)
    mb_linear = np.gradient(y_linear, dL)
    mb_sat = np.gradient(y_sat, dL)
    
    # Marginal cost (constant)
    mc = np.ones_like(L) * 0.12 * 100  # beta * 100 for scaling
    
    ax2.plot(L, mb_super, 'b-', linewidth=2.5, label='Superlinear')
    ax2.plot(L, mb_linear, 'g--', linewidth=2, label='Linear')
    ax2.plot(L, mb_sat, 'r:', linewidth=2, label='Saturating')
    ax2.plot(L, mc, 'k-', linewidth=1.5, alpha=0.7, label='Marginal cost')
    
    ax2.set_xlabel('Childhood Duration (L)', fontweight='bold')
    ax2.set_ylabel('Marginal Benefit/Cost', fontweight='bold')
    ax2.set_title('B. Marginal Returns', fontweight='bold', loc='left')
    ax2.legend(loc='upper right', frameon=True, fontsize=8)
    ax2.set_xlim(0, 20)
    ax2.set_ylim(0, 25)
    
    # Shade optimal regions
    ax2.fill_between(L[50:], mc[50:], mb_super[50:], where=mb_super[50:] > mc[50:],
                     alpha=0.2, color='blue', label='_nolegend_')
    
    # Panel C: Evolutionary outcome
    ax3 = axes[2]
    
    # Results from data
    models = ['Superlinear', 'Linear', 'Saturating', 'Null']
    dL_vals = [22.7, 17.5, 26.3, 2.3]
    dB_vals = [-1.3, -3.6, -7.8, -3.2]
    
    colors = ['#2E86AB', '#28a745', '#E74C3C', '#95a5a6']
    
    for i, (model, dL, dB, c) in enumerate(zip(models, dL_vals, dB_vals, colors)):
        ax3.scatter(dB, dL, c=c, s=200, edgecolors='black', linewidth=1.5, 
                   label=model, zorder=5)
    
    # Decoupling zone
    ax3.axvspan(-2, 2, alpha=0.2, color='green')
    ax3.axhline(y=10, color='blue', linestyle='--', alpha=0.7)
    ax3.axvline(x=-2, color='green', linestyle='--', alpha=0.7)
    ax3.axvline(x=2, color='green', linestyle='--', alpha=0.7)
    
    ax3.set_xlabel('Brain Size Change (ΔB%)', fontweight='bold')
    ax3.set_ylabel('Childhood Extension (ΔL%)', fontweight='bold')
    ax3.set_title('C. Evolutionary Outcomes', fontweight='bold', loc='left')
    ax3.legend(loc='upper left', frameon=True, fontsize=8)
    ax3.set_xlim(-10, 5)
    ax3.set_ylim(0, 35)
    
    # Label decoupling zone
    ax3.annotate('DECOUPLING\nZONE', xy=(0, 20), ha='center', fontsize=10,
                color='green', fontweight='bold',
                bbox=dict(boxstyle='round,pad=0.3', facecolor='white', alpha=0.8))
    
    plt.tight_layout()
    
    # Save
    for ext in ['png', 'pdf']:
        filepath = os.path.join(output_dir, f'Fig_S4c_mechanism_diagram.{ext}')
        plt.savefig(filepath, dpi=300, bbox_inches='tight')
        print(f'Saved: {filepath}')
    
    plt.close()


def main():
    parser = argparse.ArgumentParser(description='Visualize alternative models results')
    parser.add_argument('-i', '--input', type=str, default='alternative_models_results.csv',
                        help='Input CSV file with results')
    parser.add_argument('-o', '--output', type=str, default='.',
                        help='Output directory for figures')
    args = parser.parse_args()
    
    print("="*60)
    print("ALTERNATIVE MODELS VISUALIZATION")
    print("="*60)
    
    # Load data
    print(f"\nLoading data from: {args.input}")
    df = load_results(args.input)
    print(f"Found {len(df)} model specifications")
    
    # Create output directory if needed
    os.makedirs(args.output, exist_ok=True)
    
    # Generate figures
    print("\nGenerating figures...")
    
    print("\n1. Comparison bar plot (Fig S4a)")
    create_comparison_barplot(df, args.output)
    
    print("\n2. Forest plot (Fig S4b)")
    create_forest_plot(df, args.output)
    
    print("\n3. Summary figure (Fig S4 combined)")
    create_summary_figure(df, args.output)
    
    print("\n4. Mechanism diagram (Fig S4 mechanism)")
    create_mechanism_diagram(df, args.output)
    
    print("\n" + "="*60)
    print("COMPLETE!")
    print("="*60)
    
    # Print summary
    print("\nSUMMARY OF RESULTS:")
    print("-"*60)
    print(f"{'Model':<25} {'ΔL%':>8} {'ΔB%':>8} {'d':>6} {'Decoupling':>12}")
    print("-"*60)
    for _, row in df.iterrows():
        dec = 'YES' if row['decoupling'] else 'NO'
        print(f"{row['model_short']:<25} {row['delta_L_pct']:>+7.1f}% {row['delta_B_pct']:>+7.1f}% "
              f"{row['cohens_d']:>6.2f} {dec:>12}")
    print("-"*60)
    
    return df


if __name__ == "__main__":
    df = main()
